apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

images:
- name: goserver
  newName: micaeu/gitops-fc
  newTag: b04f71e5ca95272cc22d74d4a998f35ed100b796
